:floppy_disk:

diff --git a/bin/gh-cloneissues b/bin/gh-cloneissues
--- a/bin/gh-cloneissues
+++ b/bin/gh-cloneissues
@@ -71,6 +71,47 @@ mkdir -p ${ISSUES_DIR}
 # abysmal pergatory of unremembrance.
 start="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
 
+process_issue_events() {
+	  local _n=0
+	  local _max; _max=$(jj -i ./${ISSUES_DIR}/.response-events.json '#')
+
+	  while [[ $_n -lt $_max ]]; do
+		    echo "Processing issue events issue_number: $1 index: $_n"
+		    _j_cmd=/"$(which jj) -i ${ISSUES_DIR}/.response-events.json -n $_n"
+		    [[ ! -z $($_j_cmd) ]] || break
+
+		    _issue_number="$1"
+
+        # Ensure issue/pr for the id'd event resource actually exists.
+		    # NOTE This assumes that Issues and PRs have been downloaded before their respective comments.
+		    [[ ! -f "${ISSUES_DIR}/${_issue_number}.json" ]] && _n=$((_n + 1)) && continue
+
+		    _issueevent_number="$($_j_cmd.id)"
+
+		    $_j_cmd >"${ISSUES_DIR}/${_issue_number}_event_${_issueevent_number}.json"
+
+		    _n=$((_n + 1))
+	  done
+}
+
+get_issue_events() {
+    issue_number="$(echo $1 | sed -E 's/^0+//')"
+
+    # Sailor V preview: get lock reasons
+	  curl >${ISSUES_DIR}/.response-events.json 2>&1 \
+        --silent --show-error \
+        -H "Authorization: token ${GITHUB_TOKEN}" \
+        -H "Accept: application/vnd.github.symmetra-preview+json" \
+        -H "Accept: application/vnd.github.starfox-preview+json" \
+        -H "Accept: application/vnd.github.sailor-v-preview+json" \
+        -D "${ISSUES_DIR}/.response-events-header" \
+        'https://api.github.com/repos/'"${owner_repo}"'/issues/'${issue_number}'/events?page='$2'&per_page=100&sort=updated&since='"$(head -n1 <${ISSUES_DIR}/.state)"
+
+	  echo "Finished issues events request issue_number ${issue_number}"
+
+	  grep -v "200" ${ISSUES_DIR}/.response-events.json && process_issue_events ${1} # Use issue_number WITHOUT leading 0's trimmed
+}
+
 # It's possible these could be refactored to be DRYer.
 # But there's something to be said for saying something.
 process_issues() {
@@ -85,6 +126,12 @@ process_issues() {
 
 		_issue_number="$(printf '%05d' $($_j_cmd.number))"
 		$_j_cmd >"${ISSUES_DIR}/${_issue_number}.json"
+
+    page=1
+    while grep -q 'next' ${ISSUES_DIR}/.response-events-header || [[ $page == 1 ]]; do
+	      get_issue_events ${_issue_number} ${page}
+	      page=$((page + 1))
+    done
 
 		_n=$((_n + 1))
 	done
@@ -143,11 +190,13 @@ get_issuecomments() {
 
 onexit() {
 	rm ${ISSUES_DIR}/.response{.json,-header}
+  rm -rf ${ISSUES_DIR}/.response-events{.json,-header} # use flags to allow fail
 	echo "${start}" >${ISSUES_DIR}/.state
 }
 trap onexit EXIT
 
 touch ${ISSUES_DIR}/.response-header
+touch ${ISSUES_DIR}/.response-events-header
 
 page=1
 while grep -q 'next' ${ISSUES_DIR}/.response-header || [[ $page == 1 ]]; do
diff --git a/bin/gh-clonepullrequests b/bin/gh-clonepullrequests
--- a/bin/gh-clonepullrequests
+++ b/bin/gh-clonepullrequests
@@ -77,6 +77,133 @@ mkdir -p ${ISSUES_DIR}
 # abysmal pergatory of unremembrance.
 start="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
 
+process_issue_events() {
+	  local _n=0
+	  local _max; _max=$(jj -i ./${ISSUES_DIR}/.response-events.json '#')
+
+	  while [[ $_n -lt $_max ]]; do
+		    echo "Processing issue events issue_number: $1 index: $_n"
+		    _j_cmd=/"$(which jj) -i ${ISSUES_DIR}/.response-events.json -n $_n"
+		    [[ ! -z $($_j_cmd) ]] || break
+
+		    _issue_number="$1"
+
+        # Ensure issue/pr for the id'd event resource actually exists.
+		    # NOTE This assumes that Issues and PRs have been downloaded before their respective comments.
+		    [[ ! -f "${ISSUES_DIR}/${_issue_number}.json" ]] && _n=$((_n + 1)) && continue
+
+		    _issueevent_number="$($_j_cmd.id)"
+
+		    $_j_cmd >"${ISSUES_DIR}/${_issue_number}_event_${_issueevent_number}.json"
+
+		    _n=$((_n + 1))
+	  done
+}
+
+get_issue_events() {
+    issue_number="$(echo $1 | sed -E 's/^0+//')"
+
+    # Sailor V preview: get lock reasons
+	  curl >${ISSUES_DIR}/.response-events.json 2>&1 \
+        --silent --show-error \
+        -H "Authorization: token ${GITHUB_TOKEN}" \
+        -H "Accept: application/vnd.github.sailor-v-preview+json" \
+        -H "Accept: application/vnd.github.symmetra-preview+json" \
+        -H "Accept: application/vnd.github.starfox-preview+json" \
+        -D "${ISSUES_DIR}/.response-events-header" \
+        'https://api.github.com/repos/'"${owner_repo}"'/issues/'${issue_number}'/events?page='$2'&per_page=100&sort=updated&since='"$(head -n1 <${ISSUES_DIR}/.state)"
+
+	  echo "Finished issues events request issue_number ${issue_number}"
+
+	  grep -v "200" ${ISSUES_DIR}/.response-events.json && process_issue_events ${1} # Use issue_number WITHOUT leading 0's trimmed
+}
+
+process_issue_reviewcomments() {
+	  local _n=0
+	  local _max; _max=$(jj -i ./${ISSUES_DIR}/.response-reviewcomments.json '#')
+
+	  while [[ $_n -lt $_max ]]; do
+		    echo "Processing issue review comments issue_number: $1 review number: $2 index: $_n"
+		    _j_cmd=/"$(which jj) -i ${ISSUES_DIR}/.response-reviewcomments.json -n $_n"
+		    [[ ! -z $($_j_cmd) ]] || break
+
+		    _issue_number="$1"
+        _review_id="$2"
+
+        # Ensure issue/pr for the id'd reviews resource actually exists.
+		    # NOTE This assumes that Issues and PRs have been downloaded before their respective comments.
+		    [[ ! -f "${ISSUES_DIR}/${_issue_number}.json" ]] && _n=$((_n + 1)) && continue
+
+		    _issuereviewcomment_id="$($_j_cmd.id)"
+
+		    $_j_cmd >"${ISSUES_DIR}/${_issue_number}_review_${_review_id}_${_issuereviewcomment_id}.json"
+
+		    _n=$((_n + 1))
+	  done
+}
+
+get_issue_reviewcomments() {
+    issue_number="$1"
+    review_id="$2"
+
+    # Sailor V preview: get lock reasons
+	  curl >${ISSUES_DIR}/.response-reviewcomments.json 2>&1 \
+        --silent --show-error \
+        -H "Authorization: token ${GITHUB_TOKEN}" \
+        -H "Accept: application/vnd.github.sailor-v-preview+json" \
+        -D "${ISSUES_DIR}/.response-reviewcomments-header" \
+        'https://api.github.com/repos/'"${owner_repo}"'/pulls/'$(echo $1 | sed -E 's/^0+//')'/reviews/'${review_id}'/comments?page='$3'&per_page=100&sort=updated&since='"$(head -n1 <${ISSUES_DIR}/.state)"
+
+	  echo "Finished review comments request issue(pull) number: $1 review_id ${review_id}"
+
+	  grep -v "200" ${ISSUES_DIR}/.response-reviewcomments.json && process_issue_reviewcomments ${issue_number} ${review_id}
+}
+
+process_issue_reviews() {
+	  local _n=0
+	  local _max; _max=$(jj -i ./${ISSUES_DIR}/.response-reviews.json '#')
+
+	  while [[ $_n -lt $_max ]]; do
+		    echo "Processing issue reviews issue_number: $1 index: $_n"
+		    _j_cmd=/"$(which jj) -i ${ISSUES_DIR}/.response-reviews.json -n $_n"
+		    [[ ! -z $($_j_cmd) ]] || break
+
+		    _issue_number="$1"
+
+        # Ensure issue/pr for the id'd reviews resource actually exists.
+		    # NOTE This assumes that Issues and PRs have been downloaded before their respective comments.
+		    [[ ! -f "${ISSUES_DIR}/${_issue_number}.json" ]] && _n=$((_n + 1)) && continue
+
+		    _issuereview_id="$($_j_cmd.id)"
+
+		    $_j_cmd >"${ISSUES_DIR}/${_issue_number}_review_${_issuereview_id}.json"
+
+        page=1
+        while grep -q 'next' ${ISSUES_DIR}/.response-reviewcomments-header || [[ $page == 1 ]]; do
+	          get_issue_reviewcomments ${_issue_number} ${_issuereview_id} ${page}
+	          page=$((page + 1))
+        done
+
+		    _n=$((_n + 1))
+	  done
+}
+
+get_issue_reviews() {
+    issue_number="$(echo $1 | sed -E 's/^0+//')"
+
+    # Sailor V preview: get lock reasons
+	  curl >${ISSUES_DIR}/.response-reviews.json 2>&1 \
+        --silent --show-error \
+        -H "Authorization: token ${GITHUB_TOKEN}" \
+        -H "Accept: application/vnd.github.sailor-v-preview+json" \
+        -D "${ISSUES_DIR}/.response-reviews-header" \
+        'https://api.github.com/repos/'"${owner_repo}"'/pulls/'${issue_number}'/reviews?page='$2'&per_page=100&sort=updated&since='"$(head -n1 <${ISSUES_DIR}/.state)"
+
+	  echo "Finished issues reviews request issue_number ${issue_number}"
+
+	  grep -v "200" ${ISSUES_DIR}/.response-reviews.json && process_issue_reviews ${1} # Use issue_number WITHOUT leading 0's trimmed
+}
+
 # It's possible these could be refactored to be DRYer.
 # But there's something to be said for saying something.
 process_issues() {
@@ -97,6 +224,18 @@ process_issues() {
 			-H "Authorization: token ${GITHUB_TOKEN}" \
 			-D "${ISSUES_DIR}/.response-header" \
 			"$($_j_cmd.pull_request.patch_url)"
+
+    page=1
+    while grep -q 'next' ${ISSUES_DIR}/.response-events-header || [[ $page == 1 ]]; do
+	      get_issue_events ${_issue_number} ${page}
+	      page=$((page + 1))
+    done
+
+    page=1
+    while grep -q 'next' ${ISSUES_DIR}/.response-reviews-header || [[ $page == 1 ]]; do
+	      get_issue_reviews ${_issue_number} ${page}
+	      page=$((page + 1))
+    done
 
 		_n=$((_n + 1))
 	done
@@ -153,13 +292,56 @@ get_issuecomments() {
 	grep -v "200" ${ISSUES_DIR}/.response.json && process_issuecomments
 }
 
+process_prcomments() {
+	local _n=0
+	local _max; _max=$(jj -i ./${ISSUES_DIR}/.response.json '#')
+
+	while [[ $_n -lt $_max ]]; do
+		echo "Processing prcomment index $_n"
+		_j_cmd=/"$(which jj) -i ${ISSUES_DIR}/.response.json -n $_n"
+		[[ ! -z $($_j_cmd) ]] || break
+
+		_issue_number="$(printf '%05d' $(basename $($_j_cmd.pull_request_url)))" # HACK
+
+		# We need a way to tell Issue Comments vs. PR Comments 
+		# This assumes that Issues have been downloaded before their respective comments.
+		[[ ! -f "${ISSUES_DIR}/${_issue_number}.json" ]] && _n=$((_n + 1)) && continue
+
+		_issuecomment_number="$($_j_cmd.id)"
+
+		$_j_cmd >"${ISSUES_DIR}/${_issue_number}_prcomment_${_issuecomment_number}.json"
+
+		_n=$((_n + 1))
+	done
+}
+
+get_prcomments() {
+	# Comfort fade alert: Developer preview for multi-line comments
+  # https://developer.github.com/v3/pulls/comments/#list-comments-in-a-repository
+	curl >${ISSUES_DIR}/.response.json 2>&1 \
+		--silent --show-error \
+		-H "Authorization: token ${GITHUB_TOKEN}" \
+		-H "Accept: application/vnd.github.comfort-fade-preview+json" \
+		-D "${ISSUES_DIR}/.response-header" \
+		'https://api.github.com/repos/'"${owner_repo}"'/pulls/comments?state=all&page='$1'&per_page=100&sort=updated&since='"$(head -n1 <${ISSUES_DIR}/.state)"
+
+	echo "Finished prcomments request"
+	grep -v "200" ${ISSUES_DIR}/.response.json && process_prcomments
+}
+
 onexit() {
-	rm ${ISSUES_DIR}/.response{.json,-header}
+	# rm ${ISSUES_DIR}/.response{.json,-header}
+  # rm -rf ${ISSUES_DIR}/.response-events{.json,-header} # use flags to allow fail
+  rm -rf ${ISSUES_DIR}/.response*
 	echo "${start}" >${ISSUES_DIR}/.state
 }
 trap onexit EXIT
 
-touch ${ISSUES_DIR}/.response-header
+touch ${ISSUES_DIR}/.response{,-events,-reviews,-reviewcomments}-header
+# touch ${ISSUES_DIR}/.response-header
+# touch ${ISSUES_DIR}/.response-events-header
+# touch ${ISSUES_DIR}/.response-reviews-header
+# touch ${ISSUES_DIR}/.response-reviewcomments-header
 
 page=1
 while grep -q 'next' ${ISSUES_DIR}/.response-header || [[ $page == 1 ]]; do
@@ -171,4 +353,10 @@ page=1
 while grep -q 'next' ${ISSUES_DIR}/.response-header || [[ $page == 1 ]]; do
 	get_issuecomments ${page}
 	page=$((page + 1))
+done
+
+page=1
+while grep -q 'next' ${ISSUES_DIR}/.response-header || [[ $page == 1 ]]; do
+	  get_prcomments ${page}
+	  page=$((page + 1))
 done
